### ISSUE TITLE
Schematic Design

### ISSUE THREAD

**Issue by mikeshams** [gov466/Capstone-project#4]
Varundeep - What issues did you face when working with EasyEDA?

**Comment by varundeepsethi** [comment]
EasyEDA has a simple user interface and it was pretty easy to work on it. Some of the minor changes that I faced were -

1. We cannot create a 3D view of the schematic.
2. The inbuilt 'System' tab did not offer many components. However, the good thing was that the users were able to add their own components and we can choose from them.
3. Since it has more than 1 million free libraries, sometimes it got difficult to find the exact component that I wanted.
