### ISSUE TITLE
Interfacing ESP8266

### ISSUE THREAD

**Issue by mikeshams** [gov466/Capstone-project#7]
Sunny - 1) What issues did you face when Interfacing ESP8266 to the BBB? 2) how did you resolve them?

**Comment by MrSunnyDevgan** [comment]
the first Issue I faced was while interfacing Beaglebone with ESP8266 was that the UART code was not easily available for Beaglebone and even when we were having the right code, the UART codes are disabled by default.
We solved the problem by researching more and finding the way to activate the UART ports of Beaglebone and I found this website

https://electronics.trev.id.au/2018/02/09/get-uart-serial-ports-working-beaglebone-black/

On this website, they are activating the UART4 and we need UART1 for this task for that we need to change only a few things in this code

code from the website is -
#!/bin/sh
config-pin p9.11 uart
config-pin p9.13 uart
stty -F /dev/ttyO4 sane

changed code is -
#!/bin/sh
config-pin p9.24 uart
config-pin p9.26 uart
stty -F /dev/ttyO1 sane

and everywhere in the code, we need to change ttyO4 with ttyO1, to activate UART1 instead of UART4
