### ISSUE TITLE
interfacing buzzer/ bulb to the BBB

### ISSUE THREAD

**Issue by mikeshams** [gov466/Capstone-project#8]
Sunny - 1) What issues did you encounter when interfacing buzzer/ bulb to the BBB? 2) How did you resolve them?

**Comment by MrSunnyDevgan** [comment]
In interfacing the buzzer, I didn't face any issue because the buzzer's power requirement is not high beaglebone can supply the power, and the connection is also easy; I joined the buzzer directly to the GPIO pin.

While connecting the bulb, the first problem was that the beaglebone could give only 5V, and to turn the bulb ON; it requires 12V. So we connected the relay module in between the beaglebone and bulb. Another power source is connected to the relay module to fulfill the power requirement of the bulb.

We used two batteries of 9V and 3V connected in series to make 12V power for the bulb.

In the case of software, there was no library for beaglebone black. So we downloaded the iobbmaster.zip file from google and installed it in the backbone black. 
Instruction to install the library - first, we need to unzip the library file then put the file in the beaglebone black. The next command is to locate the file by using the command "CD" then we have to make the executable file by using the command "make" the last command is "Sudo make install" to install the library.
