### ISSUE TITLE
Interfacing ThingSpeak with Beaglebone Black

### ISSUE THREAD

**Issue by mikeshams** [gov466/Capstone-project#9]
Govind - 1) What issues did you face when Interfacing ThingSpeak with Beaglebone Black? 2) How did you fix them? 3) Why did not you have to use sstream Library Header file?

**Comment by gov466** [comment]
1,2)
 

- Since we are using beaglebone black as our main MCU and it doesnt have inbuilt WiFi functionality we were not bale to access internet, so we used ESP8266   WiFi module as a mediator to access thingspeak from beaglebone black. 

- Since we were using a cloud service for the first time we were not knowing how to access it and send data to thingspeak. It was a small issue for us. But referring to many sources in internet helped us more.

- Beaglebone black doesnt have any library for C programming to access thingspeak. Since we were  using ESP8266 -12E node mcu we were able to program it using Arduino IDE and thingspeak library was available in Arduino IDE which provides programming much easier.

- UART pins were not enable UART initially which caused error in sending data to ESP module. Single pin found in beaglebone might have more than one function. For example P9.21 can be used as PWM,SPI,UART or GPIO pins. But for each case we have to enable it accordingly.  First i enabled UART without making a script file but that was not helpfull. But after that i followed [Trevor's Electronic Blog](https://electronics.trev.id.au/2018/02/09/get-uart-serial-ports-working-beaglebone-black/) that helped me to activate which ever UART pins i want.

- Then, we were bit confused to choose between MQTT and HTTP. But after a small research around both protocols we came to a point that in our project we can use HTTP for sending data to thingspeak. We came to know that MQTT is more relevant if we use secure socket layer(SSL). SSL is used to secure credit card transactions, data transfer and logins, and more recently is becoming the norm when securing browsing of social media sites. Whereas HTTP is pretty much supported everywhere which ensures easier compatibility with firewalls. It is a more common protocol so we  feel comfortable with it. There are some differences between different MQTT implementations which might cause difficulties. HTTP strikes me as more universal and has a much larger community of people available to help you.

3) Since beaglebone wireless have inbuilt WiFi functionality we can directly send data from beaglebone to cloud. The sstream library header file which is used  for output string stream and input string stream that can be used to send both numerical or string data to thingspeak. And this header file is available in c++ only.(not in c).   Since in our project we use ESP8266 to send data to thingspeak and we use Arduino IDE  to program esp module. Arduino IDE  has special header file called "thingspeak.h" for uploading data to thingspeak, so that we no need to use sstream header file.
